version: "3.6"
services:
  
  
  portainer:
    image: "portainer/portainer"
    container_name: "portainer"
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "2000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/Data
      - /:/shared
    environment:
      - TZ=Europe/London
  qbittorrent:
    image: "linuxserver/qbittorrent"
    container_name: "qbittorrent"
    volumes:
      - ~/Documents/Docker/qbittorrent:/config
      - /:/Data
    ports:
      - "8086:8086"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=002
      - WEBUI_PORT=8086
  sabnzbd: 
    image: "linuxserver/sabnzbd"
    container_name: "sabnzbd"
    volumes:
      - ~/Documents/Docker/sabnzbd:/config
      - /:/Data
    ports:
        - "8888:8080"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - ~/Documents/Docker/radarr:/config
      - /:/Data
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "7878:7878"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - ~/Documents/Docker/sonarr:/config
      - /:/Data
      - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "8989:8989"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
  jackett:
    image: "linuxserver/jackett"
    container_name: "jackett"
    volumes:
      - ~/Documents/Docker/jackett:/config
      - /:/Data
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9117:9117"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London  
